cabal-version: 3.0
name: werewolf-server
version: 0.1.0.0
build-type: Simple

executable werewolf-server
  main-is: Main.hs
  hs-source-dirs: app
  default-language: GHC2021
  ghc-options: -Wall -Wcompat -O2 -threaded -rtsopts -with-rtsopts=-N
  build-depends:
      base >=4.17 && <5
    , bytestring >=0.11
    , http-types >=0.12
    , warp >=3.3
    , wai >=3.2

